# SITE CONFIGURATION
#url: www.vfoss.org

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""


# THEME-SPECIFIC CONFIGURATION
title: Thuy Dang                                    # site's title
#description: "Thuy Dang website with blog posts and pages"      # used by search engines
description: Researcher in Autnomous Network Management, Service Oriented Computing; OpenStack Vietnam Community Organizer; TheThingsNetwork Hanoi Initiator.
#avatar: assets/img/triangle.png                         # Empty for no avatar in navbar
# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://github.com/thuydang.png
favicon: assets/favicon.ico                             # Icon displayed in the tab

# Header and footer text
header_text: Notes on the exploration of cloud computing and mobile networking      # Change Blog header text
header_feature_image: assets/img/pexels/book-glass.jpeg
footer_text: >
  Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/sylhare/Type-on-Strap">Type on Strap</a>

# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.

# Features
katex: true                                             # Enable if using math markup
google_analytics:                                         # Tracking ID, e.g. "UA-000000-01"
# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus_shortname: thuydang-github-io


layout_variables:                                       # Open the "_sass > base" folder, and open "_variables.scss"
# Includes an icon in the footer for each username you enter
footer_icons: ["facebook", "twitter", "linkedin"]                                          # In _data/social.yml
share_buttons: facebook                                          # In _data/social.yml
authors: thuydang                                                # In _data/authors.yml
language:                                               # In _data/language.yml

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
  #style: :expanded # You might prefer to minify using :compressed
# Use the following plug-ins
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
#  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
#  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
#  - jemoji # GitHub-flavored emoji plugin for Jekyll
#  - jekyll-sitemap # Automatically generate a sitemap.xml for your Jekyll site.

# Exclude these files from your production _site
exclude: [".jekyll-cache", "Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", ".idea", "vendor/*",
          "LICENSE", "README.md", "screenshot.png", "assets/package.json", "assets/node_modules", "assets/gulpfile.js"]

#theme: type-on-strap                                  # if using the theme as a jekyll theme gem

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'


