---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

cidr_networks:
  container: 172.29.236.0/22
  tunnel: 172.29.240.0/22
  storage: 172.29.244.0/22

# https://ask.openstack.org/en/question/104307/openstack-ansible-pip-issues-while-installing-the-infrastructure/?answer=112075#post-id-112075
# FYI, when you have multiple haproxy_hosts configured in your openstack_user_config, you have to configure keepalived information. That keepalived information will be used to determine which VIP will be used on which NIC.
#
# Those VIPs can then be used in openstack-ansible, for example, by giving the dns name matching each VIP address in the openstack_user_config under the internal lb vip address / external lb vip address configuration keys. Internal and external LB VIP addresses should be different, and if possible (depends on your architecture configuration), it would be even better if they are on different NICs/networks.
#
# These lb vip addresses IPs should be reserved (still in openstack_user_config under used_ips), to make sure no container takes it.

used_ips:
  - "172.29.236.1,172.29.236.6"
  - "172.29.240.1,172.29.240.6"
  - "172.29.244.1,172.29.244.6"

global_overrides:
  # External LB VIP should be in different subnet.
  external_lb_vip_address: 172.29.236.6
  # Take reserved ip to make sure no container uses it.
  internal_lb_vip_address: 172.29.236.5
  provider_networks:
    - network:
        group_binds:
          - all_containers
          - hosts
        type: "raw"
        container_bridge: "br-mgmt"
        container_interface: "eth1"
        container_type: "veth"
        ip_from_q: "container"
        is_container_address: true
    - network:
        group_binds:
          - glance_api
          - cinder_api
          - cinder_volume
          - nova_compute
          # Uncomment the next line if using swift with a storage network.
          # - swift_proxy
        type: "raw"
        container_bridge: "br-storage"
        container_type: "veth"
        container_interface: "eth2"
        container_mtu: "9000"
        ip_from_q: "storage"
    - network:
        group_binds:
          - neutron_linuxbridge_agent
        container_bridge: "br-vxlan"
        container_type: "veth"
        container_interface: "eth10"
        container_mtu: "9000"
        ip_from_q: "tunnel"
        type: "vxlan"
        range: "1:1000"
        net_name: "vxlan"
    - network:
        group_binds:
          - neutron_linuxbridge_agent
        container_bridge: "br-ex"
        container_type: "veth"
        container_interface: "eth11"
        type: "vlan"
        range: "101:200,301:400"
        net_name: "vlan"
    - network:
        group_binds:
          - neutron_linuxbridge_agent
        container_bridge: "br-ex"
        container_type: "veth"
        container_interface: "eth12"
        host_bind_override: "eth12"
        type: "flat"
        net_name: "flat"

shared-infra_hosts:
  infra1:
    ip: 172.29.236.2

repo-infra_hosts:
  infra1:
    ip: 172.29.236.2

os-infra_hosts:
  infra1:
    ip: 172.29.236.2

identity_hosts:
  infra1:
    ip: 172.29.236.2

network_hosts:
  infra1:
    ip: 172.29.236.2

compute_hosts:
  compute1:
    ip: 172.29.236.3

storage-infra_hosts:
  infra1:
    ip: 172.29.236.2

storage_hosts:
  infra1:
    ip: 172.29.236.2
    container_vars:
      cinder_backends:
        lvm:
          volume_group: cinder-volumes
        limit_container_types: cinder_volume

haproxy_hosts:
  infra1:
    ip: 172.29.236.2

log_hosts:
  infra1:
    ip: 172.29.236.2

placement-infra_hosts:
  infra1:
    ip: 172.29.236.2
